name: dil-kursu

static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: TalhaYl/dil_kursu
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: NODE_ENV
        value: production
      - key: VUE_APP_API_URL
        value: https://${backend.HOSTNAME}/api

services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: TalhaYl/dil_kursu
    source_dir: backend
    environment_slug: node-js
    build_command: npm install
    run_command: npm start

    routes: 
      - path: /api 
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "mysql://doadmin:AVNS_HLwDvRS0t80d7QAjF3f@db-bitirmeprojesi-do-user-19908057-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=REQUIRED"
