services:
  # Backend service configuration
  backend:
    path: backend
    nixpacks:
      install:
        - npm install
      start:
        - npm start
    env:
      - NODE_ENV=production
  
  # Frontend service configuration
  frontend:
    path: frontend
    nixpacks:
      install:
        - npm install
      build:
        - npm run build
      start:
        - npm start
    env:
      - NODE_ENV=production
      - VUE_APP_API_URL=${RAILWAY_BACKEND_URL}

plugins:
  - name: mysql